### ISSUE TITLE
Maybe a typo?

### ISSUE THREAD

**Issue by trebmuh** [rncbc/qsampler#4]
Hi @rncbc , I was reading at the sources and I'm wondering if [this one](https://github.com/trebmuh/qsampler/blob/typo/src/qsamplerMainForm.ui#L445) is fine or if it should be only `<string>Toolbars</string>`instead of `<string>viewToolbars</string>`?

**Comment by rncbc** [comment]
it's a typo, should be "Toolbar", corrected on https://github.com/rncbc/qsampler/commit/2be3af5
thanks

**Comment by trebmuh** [comment]
I updated the FR translation in regards, see https://github.com/rncbc/qsampler/pull/10.
Closing here now.
